### ISSUE TITLE
DESCRIPTOR 初始化为NoneType

### ISSUE THREAD

**Issue by Rago-c** [perfdog/perfdog-service-demo-v2#1]
python3 cmd.py getdevices
--------------
Traceback (most recent call last):
  File "/Users/rago/PycharmProjects/BUI/perfdog-service-demo/cmds.py", line 4, in <module>
    from perfdog import Service
  File "/Users/rago/PycharmProjects/BUI/perfdog-service-demo/perfdog.py", line 8, in <module>
    import perfdog_pb2
  File "/Users/rago/PycharmProjects/BUI/perfdog-service-demo/perfdog_pb2.py", line 20, in <module>
    _DEVICE_EVENTTYPE = DESCRIPTOR.enum_types_by_name['DEVICE_EVENTTYPE']
AttributeError: 'NoneType' object has no attribute 'enum_types_by_name'

**Comment by CharlieDreemur** [comment]
use protobuf==4.25.1 instead can fix this problem

**Comment by perfdog** [comment]
👍
